import { z } from "zod";
import { bootstrapConfidence, complexTransferQuality, monteCarloUncertainty, roomAcousticMetrics, spatialRoomSummary, speechTransmissionScreening, uncertaintyBudget } from "../lib/measurement-science.mjs";
import { designRegularizedFir, maximumCleanOutput, optimizeComplexSources, optimizePhysicalSourceControls, polarCharacterization } from "../lib/system-science.mjs";
import { evaluationCorpusManifest, laboratoryListeningPlan, laboratoryListeningReport, sofaMetadataAssessment, spatialLayoutAssessment } from "../lib/listening-spatial.mjs";

const complexSchema = z.object({ re: z.number().finite(), im: z.number().finite() });
const uncertaintyComponent = z.object({ name: z.string().min(1).max(100), uncertainty: z.number().nonnegative(), distribution: z.enum(["normal", "rectangular", "triangular"]), coverageFactor: z.number().positive().max(10).optional(), sensitivity: z.number().finite().default(1), degreesOfFreedom: z.number().positive().max(1e9).optional() });
const corpusItem = z.object({ id: z.string().min(1).max(120), sha256: z.string().regex(/^[a-fA-F0-9]{64}$/).optional(), license: z.string().max(120).optional(), provenance: z.string().max(500).optional(), independent: z.boolean().default(false), regressionTolerance: z.number().nonnegative().optional() });

export function registerScienceTools(server, { ok, guarded }) {
  server.tool("audio_uncertainty_budget", "Propagate calibrated measurement uncertainty using GUM-style linear combination and an explicit standards-claim boundary.", { components: z.array(uncertaintyComponent).min(1).max(100), coverageProbability: z.literal(0.95).default(0.95) }, guarded(async ({ components, coverageProbability }) => ok(uncertaintyBudget(components, { coverageProbability }))));
  server.tool("audio_uncertainty_monte_carlo", "Propagate normal, rectangular, and triangular input uncertainties with deterministic JCGM-101-style Monte Carlo sampling.", { components: z.array(uncertaintyComponent).min(1).max(100), trials: z.number().int().min(1000).max(200000).default(20000), seed: z.number().int().default(1729), estimate: z.number().finite().default(0) }, guarded(async ({ components, ...options }) => ok(monteCarloUncertainty(components, options))));
  server.tool("audio_repeatability_bootstrap", "Estimate repeatability and a deterministic bootstrap confidence interval from repeated scalar measurements.", { values: z.array(z.number().finite()).min(2).max(1000), trials: z.number().int().min(1000).max(100000).default(10000), seed: z.number().int().default(2718) }, guarded(async ({ values, ...options }) => ok(bootstrapConfidence(values, options))));
  server.tool("audio_transfer_quality", "Evaluate complex transfer-function coherence, phase confidence, harmonic contamination, excitation, timing variance, and clock drift.", { bins: z.array(z.object({ frequencyHz: z.number().positive(), inputPower: z.number().nonnegative(), outputPower: z.number().nonnegative(), crossReal: z.number().finite(), crossImag: z.number().finite(), harmonicPower: z.number().nonnegative().optional(), averages: z.number().int().positive().max(100000).default(1) })).min(2).max(32768), minimumCoherence: z.number().min(0).max(1).default(0.8), maximumPhaseUncertaintyDeg: z.number().min(0.1).max(180).default(20), maximumHarmonicContaminationDb: z.number().min(-120).max(0).default(-30), minimumInputPower: z.number().positive().default(1e-12), minimumValidFraction: z.number().min(0).max(1).default(0.9), repeatTimingSeconds: z.array(z.number().finite()).max(100).default([]), repeatElapsedSeconds: z.array(z.number().finite()).max(100).default([]), maximumClockDriftPpm: z.number().positive().max(100000).default(100) }, guarded(async args => ok(complexTransferQuality(args.bins, args))));
  server.tool("audio_room_metrics", "Calculate EDT, T20/T30, C50/C80, D50, center time, decay linearity, and regression uncertainty from an impulse response.", { impulse: z.array(z.number().finite()).min(128).max(2000000), sampleRateHz: z.number().int().min(8000).max(384000), directIndex: z.number().int().nonnegative().optional(), minimumDecayRSquared: z.number().min(0).max(1).default(0.9) }, guarded(async ({ impulse, sampleRateHz, ...options }) => ok(roomAcousticMetrics(impulse, sampleRateHz, options))));
  server.tool("audio_room_spatial_summary", "Summarize position-to-position variance for room-acoustic metrics.", { positions: z.array(z.object({ clarityC50Db: z.number().finite(), clarityC80Db: z.number().finite(), definitionD50Percent: z.number().finite(), centerTimeMs: z.number().finite() })).min(2).max(100) }, guarded(async ({ positions }) => ok(spatialRoomSummary(positions))));
  server.tool("audio_speech_transmission_screening", "Calculate an IEC-60268-16-inspired speech-transmission screen from caller-supplied modulation transfer factors and importance weights.", { bands: z.array(z.object({ centerFrequencyHz: z.number().positive(), importanceWeight: z.number().nonnegative(), modulationTransferFactors: z.array(z.number().min(0).max(1)).min(1).max(32) })).min(2).max(32), redundancyPenalty: z.number().min(0).max(1).default(0) }, guarded(async ({ bands, redundancyPenalty }) => ok(speechTransmissionScreening(bands, { redundancyPenalty }))));
  server.tool("audio_polar_characterization", "Analyze guided loudspeaker polar scans and produce exploratory directivity rows with a CTA-2034 claim boundary.", { angles: z.array(z.object({ horizontalDeg: z.number().min(-180).max(180), verticalDeg: z.number().min(-90).max(90).default(0), response: z.array(z.object({ frequencyHz: z.number().positive(), levelDb: z.number().finite() })).min(2).max(4096) })).min(3).max(200) }, guarded(async ({ angles }) => ok(polarCharacterization(angles))));
  server.tool("audio_maximum_clean_output", "Evaluate a protected level ladder for output compression, coherence loss, and limiting using AES75-inspired gates.", { levelRuns: z.array(z.object({ inputLevelDb: z.number().finite(), outputLevelDb: z.number().finite(), coherence: z.number().min(0).max(1).optional(), limiterObserved: z.boolean().default(false) })).min(2).max(100), maximumCompressionDb: z.number().min(0.1).max(20).default(3), minimumCoherence: z.number().min(0).max(1).default(0.8) }, guarded(async ({ levelRuns, ...options }) => ok(maximumCleanOutput(levelRuns, options))));
  server.tool("audio_multisource_optimize", "Solve regularized complex multi-source weights across training seats and require held-out-seat evaluation before acceptance.", { trainMatrices: z.array(z.array(z.array(complexSchema).min(1).max(32)).min(1).max(32)).min(1).max(2048), heldOutMatrices: z.array(z.array(z.array(complexSchema).min(1).max(32)).min(1).max(32)).max(2048).default([]), targets: z.array(z.array(complexSchema).min(1).max(32)).min(1).max(2048), regularization: z.number().min(1e-8).max(100).default(0.01), maxGainDb: z.number().min(-30).max(20).default(6), iterations: z.number().int().min(10).max(5000).default(500) }, guarded(async args => ok(optimizeComplexSources(args))));
  server.tool("audio_multisource_physical_optimize", "Coordinate-search bounded gain, delay, polarity, and fixed crossover controls across training seats with held-out verification.", { frequenciesHz: z.array(z.number().positive()).min(1).max(512), trainMatrices: z.array(z.array(z.array(complexSchema).min(1).max(8)).min(1).max(32)).min(1).max(512), heldOutMatrices: z.array(z.array(z.array(complexSchema).min(1).max(8)).min(1).max(32)).max(512).default([]), targets: z.array(z.array(complexSchema).min(1).max(32)).min(1).max(512), constraints: z.array(z.object({ minimumDelayMs: z.number().min(0).max(100).default(0), maximumDelayMs: z.number().min(0).max(100).default(0), delayStepMs: z.number().positive().max(10).default(0.25), minimumGainDb: z.number().min(-60).max(20).default(-12), maximumGainDb: z.number().min(-60).max(20).default(6), gainStepDb: z.number().positive().max(12).default(1), polarities: z.array(z.union([z.literal(1), z.literal(-1)])).min(1).max(2).default([1, -1]), highPassHz: z.number().positive().optional(), lowPassHz: z.number().positive().optional() })).min(1).max(8), passes: z.number().int().min(1).max(10).default(3) }, guarded(async args => ok(optimizePhysicalSourceControls(args))));
  server.tool("audio_fir_design", "Design a regularized bounded mixed-phase FIR proposal and report causality, pre-ringing, latency, quantization, and deployment gates.", { measuredResponse: z.array(complexSchema).min(33).max(8193), targetResponse: z.array(complexSchema).min(33).max(8193), taps: z.number().int().min(64).max(16384).default(1024), regularization: z.number().min(1e-8).max(100).default(0.01), maxBoostDb: z.number().min(0).max(20).default(6), latencySamples: z.number().int().nonnegative().max(16383).optional(), quantizationBits: z.number().int().min(16).max(53).default(32) }, guarded(async args => ok(designRegularizedFir(args))));
  server.tool("audio_laboratory_listening_plan", "Create blinded randomized MUSHRA- or BS.1116-inspired trials with hidden-reference and anchor readiness gates.", { method: z.enum(["MUSHRA", "BS.1116"]), systems: z.array(z.object({ id: z.string().min(1).max(100), role: z.enum(["candidate", "hidden-reference", "anchor"]).default("candidate") })).min(2).max(20), trials: z.number().int().min(4).max(100).default(12), listeners: z.number().int().min(1).max(100).default(1), seed: z.string().max(200).default("audio-calibration"), excerpts: z.array(z.string().max(200)).max(100).default([]) }, guarded(async args => ok(laboratoryListeningPlan(args))));
  server.tool("audio_laboratory_listening_report", "Produce descriptive confidence and repeatability statistics for completed controlled listening trials.", { plan: z.record(z.any()), responses: z.array(z.object({ systemId: z.string().min(1).max(100), score: z.number().finite(), correct: z.boolean().optional(), repeatGroup: z.string().max(100).optional() })).min(1).max(10000) }, guarded(async ({ plan, responses }) => ok(laboratoryListeningReport(plan, responses))));
  server.tool("audio_spatial_layout_assessment", "Preflight immersive channel coordinates and head-position metadata without overstating BS.2051 compliance.", { channels: z.array(z.object({ label: z.string().min(1).max(40), azimuthDeg: z.number().finite(), elevationDeg: z.number().finite(), radiusM: z.number().positive().max(100).optional() })).min(2).max(128), listener: z.object({ x: z.number().finite(), y: z.number().finite(), z: z.number().finite() }).default({ x: 0, y: 0, z: 0 }), headPositionMetadata: z.record(z.any()).optional() }, guarded(async args => ok(spatialLayoutAssessment(args))));
  server.tool("audio_sofa_metadata_assessment", "Preflight HRTF/BRIR SOFA metadata before handing the HDF5 file to a maintained SOFA implementation.", { metadata: z.record(z.any()) }, guarded(async ({ metadata }) => ok(sofaMetadataAssessment(metadata))));
  server.tool("audio_evaluation_corpus_manifest", "Audit synthetic, external, loopback, and cross-tool reference artifacts for hashes, licenses, independence, provenance, and regression tolerances.", { synthetic: z.array(corpusItem).max(1000).default([]), external: z.array(corpusItem).max(1000).default([]), loopbacks: z.array(corpusItem).max(1000).default([]), crossTool: z.array(corpusItem).max(1000).default([]) }, guarded(async args => ok(evaluationCorpusManifest(args))));
}
